// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxmUQhBg6hG6gdxt1YJI6dfexpulp2jCY',
    appId: '1:316756438959:web:1dbd75f46602d3c352095a',
    messagingSenderId: '316756438959',
    projectId: 'flight-agent-6b9c9',
    authDomain: 'flight-agent-6b9c9.firebaseapp.com',
    storageBucket: 'flight-agent-6b9c9.firebasestorage.app',
    measurementId: 'G-SWC9H5RMM1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ0LPdEzcixwXLWF9dwmDRyxiqoB_Vte8',
    appId: '1:316756438959:android:893c1c44d9aa59de52095a',
    messagingSenderId: '316756438959',
    projectId: 'flight-agent-6b9c9',
    storageBucket: 'flight-agent-6b9c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdHuu8Ap2i2b1wDypELSZMJy7XHq0dVjw',
    appId: '1:316756438959:ios:f566a328f9245ea352095a',
    messagingSenderId: '316756438959',
    projectId: 'flight-agent-6b9c9',
    storageBucket: 'flight-agent-6b9c9.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdHuu8Ap2i2b1wDypELSZMJy7XHq0dVjw',
    appId: '1:316756438959:ios:f566a328f9245ea352095a',
    messagingSenderId: '316756438959',
    projectId: 'flight-agent-6b9c9',
    storageBucket: 'flight-agent-6b9c9.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxmUQhBg6hG6gdxt1YJI6dfexpulp2jCY',
    appId: '1:316756438959:web:89f27a8f796ca2af52095a',
    messagingSenderId: '316756438959',
    projectId: 'flight-agent-6b9c9',
    authDomain: 'flight-agent-6b9c9.firebaseapp.com',
    storageBucket: 'flight-agent-6b9c9.firebasestorage.app',
    measurementId: 'G-YVB86F977P',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDxmUQhBg6hG6gdxt1YJI6dfexpulp2jCY',
    appId: '1:316756438959:web:89f27a8f796ca2af52095a',
    messagingSenderId: '316756438959',
    projectId: 'flight-agent-6b9c9',
    authDomain: 'flight-agent-6b9c9.firebaseapp.com',
    storageBucket: 'flight-agent-6b9c9.firebasestorage.app',
    measurementId: 'G-YVB86F977P',
  );
}
